services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: >
      bash -c "
        echo '⏳ Ждём PostgreSQL...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo '✅ PostgreSQL доступен!' &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        gunicorn src.wsgi:application --bind 0.0.0.0:8000 --timeout 60 --workers 2"
    volumes:
      - .:/apps
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles

    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/staticfiles
      - ./mediafiles:/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data: